#!/bin/bash
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperA.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperA_baseline_0 --seed 0 --dist-port 29511 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperA.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperA_baseline_1 --seed 1 --dist-port 20321 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperA.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperA_baseline_2 --seed 2 --dist-port 20331 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperA.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperA_baseline_3 --seed 3 --dist-port 20341 &
wait
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperA.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperA_nmi5_0 --seed 0 --gram --c_type nmi5 --c_train_batches 4 --dist-port 29551 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperA.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperA_nmi5_1 --seed 1 --gram --c_type nmi5 --c_train_batches 4 --dist-port 20361 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperA.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperA_nmi5_2 --seed 2 --gram --c_type nmi5 --c_train_batches 4 --dist-port 20371 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperA.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperA_nmi5_3 --seed 3 --gram --c_type nmi5 --c_train_batches 4 --dist-port 20381 &
wait
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperB.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperB_baseline_0 --seed 0 --dist-port 29511 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperB.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperB_baseline_1 --seed 1 --dist-port 20321 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperB.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperB_baseline_2 --seed 2 --dist-port 20331 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperB.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperB_baseline_3 --seed 3 --dist-port 20341 &
wait
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperB.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperB_nmi5_0 --seed 0 --gram --c_type nmi5 --c_train_batches 2 --dist-port 29551 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperB.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperB_nmi5_1 --seed 1 --gram --c_type nmi5 --c_train_batches 2 --dist-port 20361 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperB.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperB_nmi5_2 --seed 2 --gram --c_type nmi5 --c_train_batches 2 --dist-port 20371 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperB.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperB_nmi5_3 --seed 3 --gram --c_type nmi5 --c_train_batches 2 --dist-port 20381 &
wait
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperC.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperC_baseline_0 --seed 0 --dist-port 29511 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperC.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperC_baseline_1 --seed 1 --dist-port 20321 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperC.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperC_baseline_2 --seed 2 --dist-port 20331 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperC.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperC_baseline_3 --seed 3 --dist-port 20341 &
wait
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperC.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperC_nmi5_0 --seed 0 --gram --c_type nmi5 --c_train_batches 1 --dist-port 29551 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperC.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperC_nmi5_1 --seed 1 --gram --c_type nmi5 --c_train_batches 1 --dist-port 20361 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperC.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperC_nmi5_2 --seed 2 --gram --c_type nmi5 --c_train_batches 1 --dist-port 20371 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperC.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperC_nmi5_3 --seed 3 --gram --c_type nmi5 --c_train_batches 1 --dist-port 20381 &
wait
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperD.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperD_baseline_0 --seed 0 --dist-port 29511 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperD.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperD_baseline_1 --seed 1 --dist-port 20321 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperD.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperD_baseline_2 --seed 2 --dist-port 20331 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperD.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperD_baseline_3 --seed 3 --dist-port 20341 &
wait
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperD.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperD_nmi5_0 --seed 0 --gram --c_type nmi5 --c_train_batches 4 --dist-port 29551 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperD.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperD_nmi5_1 --seed 1 --gram --c_type nmi5 --c_train_batches 4 --dist-port 20361 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperD.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperD_nmi5_2 --seed 2 --gram --c_type nmi5 --c_train_batches 4 --dist-port 20371 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperD.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperD_nmi5_3 --seed 3 --gram --c_type nmi5 --c_train_batches 4 --dist-port 20381 &
wait
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperE.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperE_baseline_0 --seed 0 --dist-port 29511 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperE.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperE_baseline_1 --seed 1 --dist-port 20321 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperE.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperE_baseline_2 --seed 2 --dist-port 20331 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperE.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperE_baseline_3 --seed 3 --dist-port 20341 &
wait
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperE.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperE_nmi5_0 --seed 0 --gram --c_type nmi5 --c_train_batches 2 --dist-port 29551 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperE.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperE_nmi5_1 --seed 1 --gram --c_type nmi5 --c_train_batches 2 --dist-port 20361 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperE.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperE_nmi5_2 --seed 2 --gram --c_type nmi5 --c_train_batches 2 --dist-port 20371 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperE.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperE_nmi5_3 --seed 3 --gram --c_type nmi5 --c_train_batches 2 --dist-port 20381 &
wait
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperF.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperF_baseline_0 --seed 0 --dist-port 29511 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperF.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperF_baseline_1 --seed 1 --dist-port 20321 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperF.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperF_baseline_2 --seed 2 --dist-port 20331 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperF.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperF_baseline_3 --seed 3 --dist-port 20341 &
wait
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperF.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperF_nmi5_0 --seed 0 --gram --c_type nmi5 --c_train_batches 1 --dist-port 29551 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperF.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperF_nmi5_1 --seed 1 --gram --c_type nmi5 --c_train_batches 1 --dist-port 20361 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperF.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperF_nmi5_2 --seed 2 --gram --c_type nmi5 --c_train_batches 1 --dist-port 20371 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperF.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperF_nmi5_3 --seed 3 --gram --c_type nmi5 --c_train_batches 1 --dist-port 20381 &
wait
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperG.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperG_baseline_0 --seed 0 --dist-port 29511 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperG.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperG_baseline_1 --seed 1 --dist-port 20321 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperG.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperG_baseline_2 --seed 2 --dist-port 20331 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperG.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperG_baseline_3 --seed 3 --dist-port 20341 &
wait
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperG.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperG_nmi5_0 --seed 0 --gram --c_type nmi5 --c_train_batches 4 --dist-port 29551 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperG.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperG_nmi5_1 --seed 1 --gram --c_type nmi5 --c_train_batches 4 --dist-port 20361 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperG.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperG_nmi5_2 --seed 2 --gram --c_type nmi5 --c_train_batches 4 --dist-port 20371 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperG.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperG_nmi5_3 --seed 3 --gram --c_type nmi5 --c_train_batches 4 --dist-port 20381 &
wait
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperH.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperH_baseline_0 --seed 0 --dist-port 29511 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperH.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperH_baseline_1 --seed 1 --dist-port 20321 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperH.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperH_baseline_2 --seed 2 --dist-port 20331 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperH.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperH_baseline_3 --seed 3 --dist-port 20341 &
wait
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperH.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperH_nmi5_0 --seed 0 --gram --c_type nmi5 --c_train_batches 2 --dist-port 29551 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperH.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperH_nmi5_1 --seed 1 --gram --c_type nmi5 --c_train_batches 2 --dist-port 20361 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperH.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperH_nmi5_2 --seed 2 --gram --c_type nmi5 --c_train_batches 2 --dist-port 20371 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperH.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperH_nmi5_3 --seed 3 --gram --c_type nmi5 --c_train_batches 2 --dist-port 20381 &
wait
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperI.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperI_baseline_0 --seed 0 --dist-port 29511 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperI.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperI_baseline_1 --seed 1 --dist-port 20321 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperI.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperI_baseline_2 --seed 2 --dist-port 20331 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperI.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperI_baseline_3 --seed 3 --dist-port 20341 &
wait
CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/strategies/DyRep/cifar_hyperI.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperI_nmi5_0 --seed 0 --gram --c_type nmi5 --c_train_batches 1 --dist-port 29551 &
CUDA_VISIBLE_DEVICES=3 python tools/train.py -c configs/strategies/DyRep/cifar_hyperI.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperI_nmi5_1 --seed 1 --gram --c_type nmi5 --c_train_batches 1 --dist-port 20361 &
CUDA_VISIBLE_DEVICES=5 python tools/train.py -c configs/strategies/DyRep/cifar_hyperI.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperI_nmi5_2 --seed 2 --gram --c_type nmi5 --c_train_batches 1 --dist-port 20371 &
CUDA_VISIBLE_DEVICES=6 python tools/train.py -c configs/strategies/DyRep/cifar_hyperI.yaml --model wei_vgg11Tbn --dataset cifar100 --data-path ~/datasets --experiment cifar100_wei_vgg11Tbn_hyperI_nmi5_3 --seed 3 --gram --c_type nmi5 --c_train_batches 1 --dist-port 20381 &
wait